### YamlMime:ManagedReference
items:
- uid: Postgrest.FullTextSearchConfig
  commentId: T:Postgrest.FullTextSearchConfig
  id: FullTextSearchConfig
  parent: Postgrest
  children:
  - Postgrest.FullTextSearchConfig.#ctor(System.String,System.String)
  - Postgrest.FullTextSearchConfig.Config
  - Postgrest.FullTextSearchConfig.QueryText
  langs:
  - csharp
  - vb
  name: FullTextSearchConfig
  nameWithType: FullTextSearchConfig
  fullName: Postgrest.FullTextSearchConfig
  type: Class
  source:
    remote:
      path: Postgrest/QueryFilter.cs
      branch: master
      repo: https://github.com/supabase/postgrest-csharp.git
    id: FullTextSearchConfig
    path: Postgrest/QueryFilter.cs
    startLine: 188
  assemblies:
  - Postgrest
  namespace: Postgrest
  summary: "\nConfiguration Object for Full Text Search.\nAPI Reference: http://postgrest.org/en/v7.0.0/api.html?highlight=full%20text%20search#full-text-search\n"
  example: []
  syntax:
    content: public class FullTextSearchConfig
    content.vb: Public Class FullTextSearchConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Postgrest.FullTextSearchConfig.QueryText
  commentId: P:Postgrest.FullTextSearchConfig.QueryText
  id: QueryText
  parent: Postgrest.FullTextSearchConfig
  langs:
  - csharp
  - vb
  name: QueryText
  nameWithType: FullTextSearchConfig.QueryText
  fullName: Postgrest.FullTextSearchConfig.QueryText
  type: Property
  source:
    remote:
      path: Postgrest/QueryFilter.cs
      branch: master
      repo: https://github.com/supabase/postgrest-csharp.git
    id: QueryText
    path: Postgrest/QueryFilter.cs
    startLine: 190
  assemblies:
  - Postgrest
  namespace: Postgrest
  syntax:
    content: public string QueryText { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property QueryText As String
  overload: Postgrest.FullTextSearchConfig.QueryText*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Postgrest.FullTextSearchConfig.Config
  commentId: P:Postgrest.FullTextSearchConfig.Config
  id: Config
  parent: Postgrest.FullTextSearchConfig
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: FullTextSearchConfig.Config
  fullName: Postgrest.FullTextSearchConfig.Config
  type: Property
  source:
    remote:
      path: Postgrest/QueryFilter.cs
      branch: master
      repo: https://github.com/supabase/postgrest-csharp.git
    id: Config
    path: Postgrest/QueryFilter.cs
    startLine: 193
  assemblies:
  - Postgrest
  namespace: Postgrest
  syntax:
    content: public string Config { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Config As String
  overload: Postgrest.FullTextSearchConfig.Config*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Postgrest.FullTextSearchConfig.#ctor(System.String,System.String)
  commentId: M:Postgrest.FullTextSearchConfig.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: Postgrest.FullTextSearchConfig
  langs:
  - csharp
  - vb
  name: FullTextSearchConfig(String, String)
  nameWithType: FullTextSearchConfig.FullTextSearchConfig(String, String)
  fullName: Postgrest.FullTextSearchConfig.FullTextSearchConfig(System.String, System.String)
  type: Constructor
  source:
    remote:
      path: Postgrest/QueryFilter.cs
      branch: master
      repo: https://github.com/supabase/postgrest-csharp.git
    id: .ctor
    path: Postgrest/QueryFilter.cs
    startLine: 196
  assemblies:
  - Postgrest
  namespace: Postgrest
  syntax:
    content: public FullTextSearchConfig(string queryText, string config)
    parameters:
    - id: queryText
      type: System.String
    - id: config
      type: System.String
    content.vb: Public Sub New(queryText As String, config As String)
  overload: Postgrest.FullTextSearchConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Postgrest
  commentId: N:Postgrest
  name: Postgrest
  nameWithType: Postgrest
  fullName: Postgrest
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Postgrest.FullTextSearchConfig.QueryText*
  commentId: Overload:Postgrest.FullTextSearchConfig.QueryText
  name: QueryText
  nameWithType: FullTextSearchConfig.QueryText
  fullName: Postgrest.FullTextSearchConfig.QueryText
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Postgrest.FullTextSearchConfig.Config*
  commentId: Overload:Postgrest.FullTextSearchConfig.Config
  name: Config
  nameWithType: FullTextSearchConfig.Config
  fullName: Postgrest.FullTextSearchConfig.Config
- uid: Postgrest.FullTextSearchConfig.#ctor*
  commentId: Overload:Postgrest.FullTextSearchConfig.#ctor
  name: FullTextSearchConfig
  nameWithType: FullTextSearchConfig.FullTextSearchConfig
  fullName: Postgrest.FullTextSearchConfig.FullTextSearchConfig
